### ISSUE TITLE
Duplicate columns are not handled correctly

### ISSUE THREAD

**Issue by jrober84** [phac-nml/epivizor#1]
When an input file is parsed by pandas and there are columns which have the same name, this causes the program to not parse the data correctly

**Comment by kbessonov1984** [comment]
I suggest to provide a warning to the user in the validation screen and if this issue is not fixed by deselection of the duplicated column or renaming, then refuse to upload data and show an error message

**Comment by kbessonov1984** [comment]
I implemented a simpler fix. Right now both for `csv` and `xlsx` files if there are duplicated columns user is presented with the alert message naming a duplicated column(s) and user is returned to initial home screen allowing for input file re-upload
